

# Since I have at least one submodule in this project I want to make sure it's cloned. 
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-code:
  # Currently using IDF v4.0 supplied from Espressif. 
  image: espressif/idf:release-v4.2
  stage: build
  cache:
    paths:
      - code/build
  script:
    - cd code
    - idf.py build
    - tar -zcf ../e28-cluster-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}.tar.gz build
  artifacts:
    paths:
      - e28-cluster-*.tar.gz
      - code/build/partition_table/partition-table.bin
      - code/build/bootloader/bootloader.bin
      - code/build/e28-cluster.bin

build-schematics:
  stage: build
  image: registry.gitlab.com/dowster/eeshow:latest
  script:
    - cd pcb-design
    - eeplot -o ../pcb-design-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}.pdf schematic.pro
  artifacts:
    paths:
      - pcb-design-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}.pdf