# Currently using IDF v4.0 supplied from Espressif. 
image: espressif/idf:release-v4.0

# Since I have at least one submodule in this project I want to make sure it's cloned. 
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - cd code
    - idf.py build
    - tar -zcf ../e28-cluster-${CI_COMMIT_REF_SLUG}-${CI_CONCURRENT_PROJECT_ID}.tar.gz build
  artifacts:
    paths:
      - e28-cluster-*.tar.gz
      - code/build/partition_table/partition-table.bin
      - code/build/bootloader/bootloader.bin
      - code/build/e28-cluster.bin

