language: c++

services:
  - docker

script:
  - docker run --rm -v $PWD/code:/project -w /project espressif/idf idf.py build

before_deploy:
 - tar -zcf ${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}/code/build

deploy: 
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: ${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: true