language: cpp
os: linux

services:
  - docker

script:
  - docker run --rm -v $PWD/code:/project -w /project espressif/idf idf.py build

before_deploy:
 - tar -zcf e28-cluster-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz code/build

deploy: 
  provider: releases
  token: ${GH_TOKEN}
  file: e28-cluster-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: true