language: cpp
os: linux

cache:
  directories:
    - code/build

services:
  - docker

script:
  - docker run --rm -v $PWD/code:/project -w /project espressif/idf:release-v4.0 idf.py build
  - docker run --rm -v $PWD/pcb-design:/project -w /project registry.gitlab.com/dowster/eeshow:latest eeplot -o pcb-design-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.pdf schematic.pro
before_deploy:
 - >-
   tar -cvzf e28-cluster-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz 
   code/build/partition_table/partition-table.bin 
   code/build/bootloader/bootloader.bin 
   code/build/e28-cluster.bin 
   pcb-design/pcb-design-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.pdf

deploy: 
  provider: releases
  token: ${GH_TOKEN}
  file: 
    - e28-cluster-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    - code/build/partition_table/partition-table.bin
    - code/build/bootloader/bootloader.bin
    - code/build/e28-cluster.bin
    - pcb-design/pcb-design-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.pdf

  skip_cleanup: true
  on:
    tags: true